env:
  browser: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: script
rules:
  indent:
    - 2
    - 2
    - VariableDeclarator: 2
      SwitchCase: 1
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  max-len:
    - 2
    - 80
    - 4
  complexity:
    - 1
    - 6
  no-undef: 
    - 2
  no-use-before-define:
    - 2
    - functions: false
  require-jsdoc:
    - 2
  valid-jsdoc:
    - 2
    - requireReturn: false
  no-console:
    - 0
